Update manual
savushkin-r-d/T1-PLCnext-Demo pull request #1
Opened 2022-03-28 07:33 UTC by VadimZezyotkoATP

2022-03-29 07:46 UTC, AlexandrBehunkov commented
@VadimZezyotkoATP
1. Ptusa.pcwef возможно Ptusa.pcwex
2. Для активации/деактивации входа по SSH в качестве пользователя root. Лучше использовать команду `sudo /etc/init.d/sshd restart`

2022-03-29 10:06 UTC, blackbestiya commented on docs/README.MD
> +2. [Обновление прошивки контроллера через комндную оболочку](#Обновление-прошивки-контроллера-через-комндную-оболочку)
Опечатка в слове "командную"

2022-03-29 10:11 UTC, idzm requested changes

2022-03-29 10:11 UTC, idzm commented on docs/README.MD
> +- В адресной строке ввести IP-адрес контроллера по умолчанию *10.0.16.73*
```suggestion
- В адресной строке ввести IP-адрес контроллера по умолчанию *192.168.1.10*
```

2022-03-29 10:17 UTC, blackbestiya commented on docs/README.MD
> +- Откройте комндную оболочку с помощью инструмента командной строки (например, **PuTTY**).
Опечатка в слове "командную"

2022-03-29 10:19 UTC, VadimZezyotkoATP commented on docs/README.MD
> +- Откройте комндную оболочку с помощью инструмента командной строки (например, **PuTTY**).
Что именно не так со 2 пунктом в комментарии?

2022-03-29 10:27 UTC, VadimZezyotkoATP commented
blackbestiya, А что именно не так со вторым пунктом?

2022-03-29 10:30 UTC, VadimZezyotkoATP commented
> @VadimZezyotkoATP
> 
>     1. Ptusa.pcwef возможно Ptusa.pcwex
> 
>     2. Для активации/деактивации входа по SSH в качестве пользователя root. Лучше использовать команду:
>        `sudo /etc/init.d/sshd restart`

А что именно имелось ввиду во втором пункте?

2022-03-29 10:32 UTC, blackbestiya requested changes
.

2022-03-29 10:42 UTC, blackbestiya commented on docs/README.MD
> +### Обновление прошивки контроллера через комндную оболочку
здесь тоже опечатка

2022-03-29 11:06 UTC, AlexandrBehunkov commented
> > @VadimZezyotkoATP
> > ```
> > 1. Ptusa.pcwef возможно Ptusa.pcwex
> > 
> > 2. Для активации/деактивации входа по SSH в качестве пользователя root. Лучше использовать команду:
> >    `sudo /etc/init.d/sshd restart`
> > ```
> 
> А что именно имелось ввиду во втором пункте?

Необходимо заменить команду ` sudo /etc/init.d/sshd restart.` на `sudo /etc/init.d/sshd restart`

2022-03-30 12:20 UTC, idzm requested changes

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +- Переходим на вкладку **Security** -> **User Authentication** и нажимаем на кнопку **Set Password** и задаем новый пароль для пользователя **admin** - **обратитесь к администратору**.
```suggestion
- Переходим на вкладку **Security** -> **User Authentication** и нажимаем на кнопку **Set Password** и задаем новый пароль для пользователя **admin**:
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +- Копировать файл с заменой файла библиотеки из **PtusaPLCnextEngineer.pcwlx\PROJECT\Logical%20Elements\AXCF2152_19.9.0\libPtusaPLCnextEngineer.so** в каталог **/opt/plcnext/projects/PCWE/Libs/Ptusa*
```suggestion
- Копировать файл с заменой файла библиотеки из **/AXCF2152_20.0.0.24752/Release/lib/libPtusaPLCnextEngineer.so** в каталог **/opt/plcnext/projects/PCWE/Libs/Ptusa**, где `AXCF2152_20.0.0.24752` - соответствующая версия библиотеки.
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +- Перейдите в **/opt/plcnext/projects/PCWE/Libs/Ptusa** каталог (команда: *cd /opt/plcnext/projects/PCWE/Libs/Ptusa*).
Это не обязательно:
```suggestion
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +- Запускаем PLCnext Engineer, открываем файл проекта, который находится в данном каталоге **p:\PTUSA projects\projects\T1_PLCNext_Demo\PLCnext\Ptusa.pcwex**.
```suggestion
- Запускаем PLCnext Engineer, открываем файл проекта, который находится в данном каталоге **PLCnext Engineer\T1-PLCNext-Demo.pcwex**.
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +
```suggestion
Для этого предлагается использовать программу [WinSCP](https://winscp.net/eng/index.php).

```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +Выбираем файлы проекта, которые необходимо записать на контроллер. Данные файлы находятся в следующем каталоге: **P:\PTUSA projects\projects\Название проекта**. Список файлов, описывающих проект:
```suggestion
Выбираем файлы проекта, которые необходимо записать на контроллер. Данные файлы находятся в текущем каталоге проекта. Список файлов, описывающих проект:
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +Копируем данные файлы на контроллер. Также необходимо скопировать системные файлы из каталога **p:\PTUSA projects\system scripts**. Список системных файлов:
```suggestion
Копируем данные файлы на контроллер. Также необходимо скопировать системные файлы (каталог **sys**). Список системных файлов:
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +- __*sys.rm_PACs.lua*__ - удаленная работа с другими *PAC*;
Устарело, уже не нужен:
```suggestion
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +- __*main.rm_PACs.lua*__ - описание взаимодействия с удаленными PAC.
Устарело, уже не нужен:
```suggestion
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +- __*main.wago.lua*__ - описание привязки устройств к модулям Wago;
Устарело, новое имя:
```suggestion
- __*main.io.lua*__ - описание привязки устройств к модулям ввода/вывода;
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +
```suggestion
- __*prg.lua*__ - описание аппаратов, агрегатов.

```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +- __*sys.wago.lua*__ - описание модулей ввода-вывода *Wago*;
Устарело, новое название:
```suggestion
- __*sys.io.lua*__ - описание модулей ввода-вывода;
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +- __*boiler.lua*__ - описание типового технологического *агрегата* **узел нагрева**.
В данном проекте эти файлы не используются:
```suggestion
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +Далее после ввода пароля текущего пользователя задаем пароль для **root** .Текущий пароль **1111**:
```suggestion
Далее после ввода пароля текущего пользователя задаем пароль для **root** .
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +- Подключитесь к контроллеру и войдите в систему **admin** - **обратитесь к администратору**
```suggestion
- Подключитесь к контроллеру и войдите в систему **admin**.
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +- В разделе #Authentication: раскомментируйте закомментированную запись. #PermitRootLogin yes.
```suggestion
- В разделе #Authentication: раскомментируйте запись: `#PermitRootLogin yes`.
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +- Подключитесь к контроллеру и войдите в систему **admin** - **обратитесь к администратору**
```suggestion
- Подключитесь к контроллеру и войдите в систему **admin**.
```

2022-03-30 12:20 UTC, idzm commented on docs/README.MD
> +далее вводим пароль(**1111**). После успешного переключения отображется соответствующее приглашение командной строки:
```suggestion
далее вводим пароль. После успешного переключения отображается соответствующее приглашение командной строки:
```

2022-03-31 05:22 UTC, AlexandrBehunkov commented on docs/README.MD
> +Указываем для найденного контроллера его соответствие в проекте. Для этого нужно прописать MAC address, указанный на корпусе :
```suggestion
Указываем для найденного контроллера его соответствие в проекте. Для этого нужно выбрать контроллер с необходимым MAC address, указанный на корпусе :
```

2022-03-31 05:24 UTC, AlexandrBehunkov commented on docs/README.MD
> +- Копировать файл с заменой файла библиотеки из **/AXCF2152_20.0.0.24752/Release/lib/libPtusaPLCnextEngineer.so** в каталог **/opt/plcnext/projects/PCWE/Libs/Ptusa**, где `AXCF2152_20.0.0.24752` - со
```suggestion
- Копировать файл с заменой файла библиотеки из **/AXCF2152_21.0.3.35554/Release/lib/libPtusaPLCnextEngineer.so** в каталог **/opt/plcnext/projects/PCWE/Libs/Ptusa**, где `AXCF2152_21.0.3.35554` - соответствующая версия библиотеки.
```

2022-03-31 05:24 UTC, AlexandrBehunkov commented on docs/README.MD
> +- Копировать файл с заменой файла библиотеки из **/AXCF2152_20.0.0.24752/Release/lib/libPtusaPLCnextEngineer.so** в каталог **/opt/plcnext/projects/PCWE/Libs/Ptusa**, где `AXCF2152_20.0.0.24752` - со
Лучше указать актуальную версию.

2022-03-31 05:27 UTC, AlexandrBehunkov commented on docs/README.MD
> +
Необходимо описать, как происходит настройка через заданную утилиту.

2022-04-05 13:19 UTC, AlexandrBehunkov commented
@VadimZezyotkoATP не исправлены все замечания, указанные @idzm.

2022-04-06 12:34 UTC, alexandraneroda commented on docs/README.MD
> +При необходимости меняем сетевые настройки устройств проекта на данной странице.
При необходимости, меняем сетевые настройки устройств проекта на данной странице.

2022-04-06 12:37 UTC, alexandraneroda commented on docs/README.MD
> +- Откройте комндную оболочку с помощью инструмента командной строки (например, **KiTTY**).
Откройте командную оболочку с помощью инструмента командной строки (например, **KiTTY**).

2022-04-06 12:42 UTC, alexandraneroda commented on docs/README.MD
> +Для остановки и запуска проекта необходимо выполнить следующие команду в консоли:
Для остановки и запуска проекта необходимо выполнить следующие команды в консоли:

2022-04-07 07:49 UTC, idzm requested changes

2022-04-07 07:49 UTC, idzm commented on docs/README.MD
> +Проект для тестового стенда **PLCnext**.
```suggestion
```

2022-04-07 07:49 UTC, idzm commented on docs/README.MD
> +# Настройка контроллера на примере проекта **T1_PLCNext_Demo**.
```suggestion
# Настройка контроллера на примере проекта тестового стенда **T1_PLCNext_Demo**.
```

2022-04-07 07:49 UTC, idzm commented on docs/README.MD
> +Копируем каталог проекта *PLCnext*, который находится здесь - **p:\PTUSA projects\projects\default\PLCnext** - в каталог требуемого проекта в подкаталог **PLCnext**.
```suggestion
Копируем каталог проекта *PLCnext*, который находится здесь - **https://github.com/savushkin-r-d/T1-PLCnext-Demo/releases/latest** - в каталог проекта в подкаталог **PLCnext Engineer**.
```

2022-04-07 07:49 UTC, idzm commented on docs/README.MD
> +## Создание нового проекта на основе базового ##
```suggestion
## Создание проекта PLCnext Engineer ##
```

2022-04-07 07:49 UTC, idzm commented on docs/README.MD
> +Также необходимо скопировать системные файлы из каталога **p:\PTUSA projects\system scripts**. Список системных файлов:
```suggestion
Также необходимо скопировать системные файлы из каталога **sys**. Список системных файлов:
```

2022-04-07 07:59 UTC, idzm approved these changes

2022-04-07 08:23 UTC, merged