Update project 2022
savushkin-r-d/T1-PLCnext-Demo pull request #3
Opened 2022-04-01 09:40 UTC by VadimZezyotkoATP

Added automatic defense

2022-04-07 08:27 UTC, AlexandrBehunkov commented on IOL-Conf/A104.lrp
> +            <Param id="V_AEP2" subindex="" internalValue="1005" name="AEP2" value="100.5" unit="°C" />
Данный параметр правился вручную?

2022-04-08 06:01 UTC, VadimZezyotkoATP commented on IOL-Conf/A104.lrp
> +            <Param id="V_AEP2" subindex="" internalValue="1005" name="AEP2" value="100.5" unit="°C" />
Нет, правился автоматически.

2022-04-08 10:53 UTC, idzm requested changes
Надо оставить сетевые адреса контроллера и узла ввода\вывода.

2022-04-08 10:53 UTC, idzm commented on main.io.lua
> +        IP      = '10.0.16.73',
```suggestion
        IP      = '192.168.1.10',
```

2022-04-08 10:53 UTC, idzm commented on main.io.lua
> +        IP      = '10.0.16.74',
```suggestion
        IP      = '192.168.1.11',
```

2022-04-11 06:11 UTC, AlexandrBehunkov submitted a review, later dismissed

2022-04-18 09:49 UTC, idzm approved these changes

2022-04-18 09:50 UTC, merged