Add instruction
savushkin-r-d/T1-PLCnext-Demo pull request #8
Opened 2022-12-13 12:13 UTC by Vasiliysamuilik

Add instruction to run the controller in simulation mode

2022-12-13 13:57 UTC, VadimZezyotkoATP commented
@Vasiliysamuilik
1. Думаю нужно отметить, что при указании в инструкции путей установки данных приложений  нужно создать отдельный новый диск (P) на ПК.
2. Глава "Установка и настройка EasyServer"  заканчивается на загрузке файла базы каналов, откуда берётся проект?
3. Для чего нужно изменять IP адрес в "DbEditorXML"?

2022-12-14 07:45 UTC, alexandraneroda commented on docs/README.MD
> +### Обновление библиотеки через командную оболочку
```suggestion
### Обновление библиотеки через командную облочку
```

2022-12-14 07:52 UTC, VadimZezyotkoATP commented on docs/README.MD
> + - В появившемся окне заполнить данные которые указаны на рисунке 8 и нажать "Ок".
```suggestion
 - В появившемся окне заполнить данные которые указаны на рисунке 33 и нажать "Ок".
```

2022-12-14 08:36 UTC, alexandraneroda commented on docs/README.MD
> + Проект T1_PLCNext_Demo находится [здесь](https://github.com/savushkin-r-d/T1-PLCnext-Demo).
```suggestion
 Проет T1_PLCNext_Demo находится [здесь](https://github.com/savushkin-r-d/T1-PLCnext-Demo).
```

2022-12-15 17:31 UTC, alexandraneroda requested changes

2022-12-15 17:31 UTC, alexandraneroda commented on docs/README.MD
> + - После этого в папке P:\Monitor запускаем приложение Bugger.exe, нажимаем "Показать" и проверяем успешно ли загружен сервер.
```suggestion
 - После этого в папке P:\Monitor запускаем приложение Bugger.exe, нажимаем "Показать" и проверяем, успешно ли загружен сервер.
```

2022-12-15 17:31 UTC, alexandraneroda commented on docs/README.MD
> + - В появившемся окне заполнить данные которые указаны на рисунке 33 и нажать "Ок".
```suggestion
 - В появившемся окне заполнить данные, которые указаны на рисунке 34 и нажать "Ок".
```

2022-12-15 17:31 UTC, alexandraneroda commented on docs/README.MD
> + - запустить и собрать проект T1_PLCNext_Demo в Visual Studio Code (для сборки проекта следует создать рабочую облать проекта и установить все необходимые расширения, затем в верхнем меню Visual Stud
```suggestion
 - запустить и собрать проект T1_PLCNext_Demo в Visual Studio Code (для сборки проекта следует создать рабочую область проекта и установить все необходимые расширения, затем в верхнем меню Visual Studio Code нажать "Терминал / Запустить задачу сборки" либо использовать сочетание клавиш "CTL + SHIFT + B").
```

2022-12-15 17:31 UTC, alexandraneroda commented on docs/README.MD
> + ## После выполнения всех шагов необходимо:
```suggestion
 ## Запуск и сборка проекта:
```

2022-12-15 17:31 UTC, alexandraneroda commented on docs/README.MD
> + - Далее во вкладке "Устройства" выбираем "T1_PLCNext_Demo" и изменяеем IP адрес на 127.0.0.1. Это необходимо для локального подключения.
```suggestion
 - Далее во вкладке "Устройства" выбираем "T1_PLCNext_Demo" и изменяем IP адрес на 127.0.0.1. Это необходимо для локального подключения.
```

2022-12-15 17:31 UTC, alexandraneroda commented on docs/README.MD
> + - Далее переходим во вкладку "Настройка базы каналов" и доваляем файл "T1_PLCNext_Demo.cdbx", находящийся в папке P:\Monitor\chbase\T1_PLCNext_Demo.cdbx
```suggestion
 - Далее переходим во вкладку "Настройка базы каналов" и добавляем файл "T1_PLCNext_Demo.cdbx", находящийся в папке P:\Monitor\chbase\T1_PLCNext_Demo.cdbx
```

2022-12-15 17:31 UTC, alexandraneroda commented on docs/README.MD
> + ## DbEditorXML
```suggestion
 ## Настройка DbEditorXML
```

2022-12-15 17:31 UTC, alexandraneroda commented on docs/README.MD
> + 6. [Установка и настройка Monitor](#Установка-и-настройка-Monitor)
```suggestion
 6. [Установка и настройка Monitor](#Установка-и-настройка-Monitor)
 7. [Запуск и сборка проекта](#Запуск-и-сборка-проекта)
```

2022-12-16 16:28 UTC, alexandraneroda requested changes

2022-12-16 16:28 UTC, alexandraneroda commented on docs/README.MD
> + 4. [Установка и настройка Easy Server](#Установка-и-настройка-Easy-Server)
```suggestion
 4. [Установка и настройка EasyServer](#Установка-и-настройка-EasyServer)
```

2022-12-16 16:28 UTC, alexandraneroda commented on docs/README.MD
> + 4. [Установка и настройка Easy Server](#Установка-и-настройка-Easy-Server)
Не работала ссылка

2022-12-19 08:02 UTC, alexandraneroda requested changes

2022-12-19 08:02 UTC, alexandraneroda commented on docs/README.MD
> + Easy Server находится в папке P:\Monitor\EasyServer.
```suggestion
 Easy Server находится в папке P:\Monitor\EasyServer.exe
```

2022-12-19 08:51 UTC, alexandraneroda commented on docs/README.MD
> +
Нужно добавить описание к добавлению базы каналов. В первую очередь добавляется база каналов, а уже потом загружается проект. На скриншоте загружен проект и нет описания.

2022-12-19 08:55 UTC, alexandraneroda commented on docs/README.MD
> + - Переходим во вкладку "Настройки проектов" и добавляем файл "T1_PLCNext_Demo.mpr", находящийся в папке P:\Monitor\projects\T1_PLCNext_Demo.mpr
```suggestion
 - Переходим во вкладку "Проекты" и добавляем файл "T1_PLCNext_Demo.mpr", находящийся в папке P:\Monitor\projects\T1_PLCNext_Demo.mpr
```

2022-12-19 09:09 UTC, alexandraneroda commented on docs/README.MD
> + - Необходимо запустить файл Monotior.exe.
```suggestion
 - Необходимо запустить файл Monitor.exe.
```

2022-12-19 09:12 UTC, alexandraneroda commented on docs/README.MD
> + - запустить и собрать проект T1_PLCNext_Demo в Visual Studio Code (для сборки проекта следует создать рабочую область проекта и установить все необходимые расширения, затем в верхнем меню Visual Stu
"Необходимые расширения" - это какие конкретно?

2022-12-19 10:24 UTC, alexandraneroda approved these changes

2022-12-19 10:37 UTC, alexandraneroda submitted a review, later dismissed

2022-12-20 05:53 UTC, VadimZezyotkoATP commented
Пункт 4 и  5 нужно поменять местами.

2022-12-20 06:59 UTC, VadimZezyotkoATP requested changes

2022-12-20 06:59 UTC, VadimZezyotkoATP commented on docs/README.MD
> + - запустить и собрать проект T1_PLCNext_Demo в Visual Studio Code (для сборки проекта следует создать рабочую область проекта и установить все необходимые расширения, затем в верхнем меню Visual Stu
```suggestion
Описание управляющей программы реализовано в виде Lua-скриптов.

Для запуска сначала необходимо открыть папку проекта в редакторе на своей локальной рабочей машине.
Используем редактор Visual Studio Code. 

- Открываем папку проекта- "P:\PTUSA-projects\T1_PLCNext_Demo" 

Для тестирования проекта в меню сверху выбираем "Файл"->"Открыть рабочую область из файла"-> "Выбираем файл рабочей области: ( _P:\PTUSA-projects\T1_PLCNext_Demo\project.code-workspace_)".

- Тестирование проекта в VS Code осуществляется несколькими способами:

1. "Терминал" -> "Запуск задачи" -> "Debug run project";

2. Комбинация клавиш CTRL+SHIFT+B.

- Остановка тестирования осуществляется несколькими способами:

1. "Терминал" -> "Завершить задачу";

2. Комбинация клавиш CTRL+С при активном фокусе окна консоли. В данном случае содержимое консоли не очищается;

3. Закрыть редактор VS-Code.

```

2022-12-20 13:12 UTC, alexandraneroda commented on docs/README.MD
> +3. Закрыть редактор VS-Code.
@VadimZezyotkoATP, данный подпункт точно должен относится к этому пункту или должен быть отдельным пунктом?

2022-12-22 05:06 UTC, VadimZezyotkoATP commented on docs/README.MD
> +3. Закрыть редактор VS-Code.
@alexandraneroda, думаю можно убрать.

2022-12-22 07:39 UTC, alexandraneroda requested changes

2022-12-22 07:39 UTC, alexandraneroda commented on docs/README.MD
> +3. Закрыть редактор VS-Code.
```suggestion
```

2022-12-23 08:21 UTC, alexandraneroda approved these changes

2022-12-27 07:54 UTC, idzm requested changes

2022-12-27 07:54 UTC, idzm commented on docs/README.MD
> + 6. [Установка и настройка Monitor](#Установка-и-настройка-Monitor)
Надо содержание переместить в начало - так удобнее читать.

2022-12-27 07:54 UTC, idzm commented on docs/README.MD
> +# Запуск в режиме симуляции (эмулятор "на столе")
Данный раздел предлагаю сделать первым - не у всех есть в наличии контроллер.

2022-12-28 12:18 UTC, idzm requested changes

2022-12-28 12:18 UTC, idzm commented on docs/README.MD
> +## Запуск и сборка проекта:
```suggestion
## Запуск и сборка проекта
```

2022-12-28 12:18 UTC, idzm commented on docs/README.MD
> +Для тестирования проекта в меню сверху выбираем "Файл" -> "Открыть рабочую область из файла" -> "Выбираем файл рабочей области: (_P:\PTUSA-projects\T1_PLCNext_Demo\project.code-workspace_)".
```suggestion
Для тестирования проекта в меню сверху выбираем "Файл" -> "Открыть рабочую область из файла" -> "Выбираем файл рабочей области: (_P:\PTUSA-projects\T1_PLCNext_Demo\project.code-workspace_)".
```

2022-12-28 12:18 UTC, idzm commented on docs/README.MD
> +В Monitor будут видны все устройства проекта тестового стенда T1_PLCNext_Demo с возможностью управления.
Здесь предлагаю вставить картинки, поясняющие что проект успешно запустился и идёт обмен с управляющей программой, которая запущена локально на компьютере.

2023-01-03 09:53 UTC, alexandraneroda commented on docs/README.MD
> +<p align="center"> Рисунок 30 - Выбор модели баскаплера</p>
```suggestion
<p align="center"> Рисунок 30 - Выбор модели баскаплера</p>
```

2023-01-03 09:54 UTC, alexandraneroda requested changes

2023-01-03 09:54 UTC, alexandraneroda commented on docs/README.MD
> +### Установка Git LFS
```suggestion
## Установка Git LFS
```

2023-01-03 10:01 UTC, alexandraneroda requested changes

2023-01-03 10:01 UTC, alexandraneroda commented on docs/README.MD
> +<p align="center"> Рисунок 26 - Задание пароля в веб-браузере  </p>
```suggestion
<p align="center"> Рисунок 29 - Задание пароля в веб-браузере  </p>
```

2023-01-03 10:01 UTC, alexandraneroda commented on docs/README.MD
> +<p align="center"> Рисунок 27 - Запуск проекта</p>
```suggestion
<p align="center"> Рисунок 30 - Запуск проекта</p>
```

2023-01-03 10:01 UTC, alexandraneroda commented on docs/README.MD
> +<p align="center"> Рисунок 28 - Просмотр сообщений </p>
```suggestion
<p align="center"> Рисунок 31 - Просмотр сообщений </p>
```

2023-01-03 10:01 UTC, alexandraneroda commented on docs/README.MD
> +<p align="center"> Рисунок 30 - Выбор модели баскаплера</p>
```suggestion
<p align="center"> Рисунок 33 - Выбор модели баскаплера</p>
```

2023-01-03 10:01 UTC, alexandraneroda commented on docs/README.MD
> +<p align="center"> Рисунок 31 - Настройка сетевых параметров</p>
```suggestion
<p align="center"> Рисунок 34 - Настройка сетевых параметров</p>
```

2023-01-03 10:01 UTC, alexandraneroda commented on docs/README.MD
> +<p align="center"> Рисунок 32 - Настройка сетевых параметров</p>
```suggestion
<p align="center"> Рисунок 35 - Настройка сетевых параметров</p>
```

2023-01-03 10:01 UTC, alexandraneroda commented on docs/README.MD
> +<p align="center"> Рисунок 33 - Настройка сетевых параметров</p>
```suggestion
<p align="center"> Рисунок 36 - Настройка сетевых параметров</p>
```

2023-01-03 10:01 UTC, alexandraneroda commented on docs/README.MD
> +<p align="center"> Рисунок 34 - Общий вид</p>
```suggestion
<p align="center"> Рисунок 37 - Общий вид</p>
```

2023-01-03 11:33 UTC, alexandraneroda approved these changes

2023-01-03 11:44 UTC, alexandraneroda requested changes

2023-01-03 11:44 UTC, alexandraneroda commented on docs/README.MD
> +- В появившемся окне заполнить данные, которые указаны на рисунке 34 и нажать "Ок".
```suggestion
- В появившемся окне заполнить данные, которые указаны на рисунке 10 и нажать "Ок".
```

2023-01-03 11:54 UTC, alexandraneroda approved these changes

2023-01-03 12:30 UTC, idzm approved these changes

2023-01-03 12:48 UTC, VadimZezyotkoATP approved these changes

2023-01-03 13:27 UTC, Serega-pixel approved these changes

2023-01-04 06:55 UTC, merged