Add instructions for interacting with Bus Coupler
savushkin-r-d/T1-PLCnext-Demo pull request #9
Opened 2023-01-16 14:16 UTC by Vasiliysamuilik

2023-01-17 05:00 UTC, AlexandrBehunkov requested changes
@Vasiliysamuilik Если мы задаем адрес компьютера 192.168.1.1, то при выполнении следующего пункта
**Проверяем пингуется ли локальный контроллер. В командной строке прописываем команду "ping 192.168.1.1"**
 мы пингуем сами себя.

2023-01-17 09:15 UTC, idzm requested changes

2023-01-17 09:15 UTC, idzm commented on docs/README.MD
> +- Проверяем пингуется ли компьютер. В командной строке прописываем команду "ping 192.168.1.1".
```suggestion
- Проверяем корректность настройки локальной сети Bus Coupler. В командной строке прописываем команду "ping 192.168.1.1".
```

2023-01-17 09:15 UTC, idzm commented on docs/README.MD
> +- Проверяем пингуется ли Bus Coupler. В командной строке прописываем команду "ping 192.168.1.11".
```suggestion
- Проверяем наличие связи с Bus Coupler. В командной строке прописываем команду "ping 192.168.1.11".
```

2023-01-17 09:15 UTC, idzm commented on docs/README.MD
> +- В браузере прописываем IP-адрес: 192.168.1.11 и нажимаем "Enter" после чего приозойдёт переход на стартовую страницу Bus Coupler.
```suggestion
- В браузере прописываем IP-адрес: 192.168.1.11 и нажимаем "Enter", после чего произойдёт переход на стартовую страницу Bus Coupler.
```

2023-01-18 06:20 UTC, idzm approved these changes

2023-01-18 06:21 UTC, KUZMA-1989 approved these changes

2023-01-18 06:23 UTC, AlexandrBehunkov approved these changes

2023-01-18 06:25 UTC, merged